<?php

return [
    'countries' => [
        'GB' => [
            'zones' => [
                'London',
                'Bedfordshire',
                'Berkshire',
                'Bristol',
                'Buckinghamshire',
                'Cambridgeshire',
                'Cheshire',
                'Cornwall and Isles of Scilly',
                'Cumbria',
                'Derbyshire',
                'Devon',
                'Dorset',
                'Durham',
                'East Riding of Yorkshire',
                'East Sussex',
                'Essex',
                'Gloucestershire',
                'Greater London',
                'Greater Manchester',
                'Hampshire',
                'Herefordshire',
                'Hertfordshire',
                'Isle of Wight',
                'Kent',
                'Lancashire',
                'Leicestershire',
                'Lincolnshire',
                'Merseyside',
                'Norfolk',
                'North Yorkshire',
                'Northamptonshire',
                'Northumberland',
                'Nottinghamshire',
                'Oxfordshire',
                'Rutland',
                'Shropshire',
                'Somerset',
                'South Yorkshire',
                'Staffordshire',
                'Suffolk',
                'Surrey',
                'Tyne and Wear',
                'Warwickshire',
                'West Midlands',
                'West Sussex',
                'West Yorkshire',
                'Wiltshire',
                'Worcestershire',
                'Flintshire',
                'Glamorgan',
                'Merionethshire',
                'Monmouthshire',
                'Montgomeryshire',
                'Pembrokeshire',
                'Radnorshire',
                'Anglesey',
                'Breconshire',
                'Caernarvonshire',
                'Cardiganshire',
                'Carmarthenshire',
                'Denbighshire',
                'Kirkcudbrightshire',
                'Lanarkshire',
                'Midlothian',
                'Moray',
                'Nairnshire',
                'Orkney',
                'Peebleshire',
                'Perthshire',
                'Renfrewshire',
                'Ross & Cromarty',
                'Roxburghshire',
                'Selkirkshire',
                'Shetland',
                'Stirlingshire',
                'Sutherland',
                'West Lothian',
                'Wigtownshire',
                'Aberdeenshire',
                'Angus',
                'Argyll',
                'Ayrshire',
                'Banffshire',
                'Berwickshire',
                'Bute',
                'Caithness',
                'Clackmannanshire',
                'Dumfriesshire',
                'Dumbartonshire',
                'East Lothian',
                'Fife',
                'Inverness',
                'Kincardineshire',
                'Kinross-shire',
                'Antrim',
                'Armagh',
                'Down',
                'Fermanagh',
                'Londonderry',
                'Tyrone',
            ],
        ],
    ],
];

